import { type Metadata } from 'next'
import '../globals.css'
import localFont from 'next/font/local';
import { SidebarProvider } from '@/components/ui/sidebar';

const NunitoSans = localFont({
  src: '../fonts/NunitoSans.woff2',
  variable: '--font-NunitoSans',
  weight: "100 900",
})

export const metadata: Metadata = {
  title: 'CMS CMLabs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <SidebarProvider>
      <html lang='en'>
        <body className={`${NunitoSans.variable} antialiased`}>
          { children }
        </body>
      </html>
    </SidebarProvider>
  )
}