import { type Metadata } from 'next'
import '../globals.css'
import localFont from 'next/font/local';
import { SidebarProvider } from '@/components/ui/sidebar';
import  AppSidebar  from '@/components/AppSidebar';
import { ThemeProvider } from '@/components/ThemeProvider';

const NunitoSans = localFont({
  src: '../fonts/NunitoSans.woff2',
  variable: '--font-NunitoSans',
  weight: "100 900",
})

export const metadata: Metadata = {
  title: 'CMS CMLabs',
  description: 'Generated by create next app',
}

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
          <html lang='en' suppressHydrationWarning>
            <body className={`${NunitoSans.variable} antialiased`}>
              <ThemeProvider
                attribute="class"
                defaultTheme='system'
                enableSystem
                disableTransitionOnChange
                >
                { children }
              </ThemeProvider>
          </body>
        </html>
    </SidebarProvider>
  )
}