export const metadata = {
  title: 'CMS CMLabs',
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    { children }
  )
}