import { type Metadata } from 'next'
import '../globals.css'
import localFont from 'next/font/local';

const NunitoSans = localFont({
  src: '../fonts/NunitoSans.woff2',
  variable: '--font-NunitoSans',
  weight: "100 900",
})

export const metadata: Metadata = {
  title: 'CMS CMLabs',
  description: 'Generated by create next app',
}

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${NunitoSans.variable} antialiased`}>
          { children }
      </body>
    </html>
  )
}